// Generated by scripts/build-track-encyclopedia.mjs. Do not edit by hand.
import type { TrackEncyclopediaAlbumEntry } from "../../types";

export const trackEncyclopediaMetadata = {
  "version": "1.0.0-pilot",
  "generatedAt": "2026-09-19T00:00:00Z",
  "albumCount": 9
} as const;

export const trackEncyclopediaAlbums = {
  "001-marvin-gaye-what-s-going-on-fd00dde9": {
    albumId: "001-marvin-gaye-what-s-going-on-fd00dde9",
    editionNumber: 5,
    contentHash: "b35fcb8c1fb0a2a1",
    objectHash: "a3251e02645e1b828f32381c974fa1d82a61b3ec912df2f88c345f8e50d0fc28",
    trackCount: 9,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/a3251e02645e1b828f32381c974fa1d82a61b3ec912df2f88c345f8e50d0fc28.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/a3251e02645e1b828f32381c974fa1d82a61b3ec912df2f88c345f8e50d0fc28.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "002-the-beach-boys-pet-sounds-eabcc325": {
    albumId: "002-the-beach-boys-pet-sounds-eabcc325",
    editionNumber: 2,
    contentHash: "087bfa79d706c8ae",
    objectHash: "fbd7c63d9cd0488ed599adad29d957b29f16afae6579b35539c6a4460d4a7d3f",
    trackCount: 13,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/fbd7c63d9cd0488ed599adad29d957b29f16afae6579b35539c6a4460d4a7d3f.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/fbd7c63d9cd0488ed599adad29d957b29f16afae6579b35539c6a4460d4a7d3f.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "003-joni-mitchell-blue-9c3a8b85": {
    albumId: "003-joni-mitchell-blue-9c3a8b85",
    editionNumber: 2,
    contentHash: "26b222e5aef9db55",
    objectHash: "cb7afcee2ceb8f5f33cd471b55b674ea359099ee15973d19b4949c36da414476",
    trackCount: 10,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/cb7afcee2ceb8f5f33cd471b55b674ea359099ee15973d19b4949c36da414476.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/cb7afcee2ceb8f5f33cd471b55b674ea359099ee15973d19b4949c36da414476.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "004-stevie-wonder-songs-in-the-key-of-life-0518d4f8": {
    albumId: "004-stevie-wonder-songs-in-the-key-of-life-0518d4f8",
    editionNumber: 3,
    contentHash: "bc1413dab6a4d0ab",
    objectHash: "61e886618870cfc0839956c88ad5fa7c134bb056376130b0aed6a7ab98d52024",
    trackCount: 21,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/61e886618870cfc0839956c88ad5fa7c134bb056376130b0aed6a7ab98d52024.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/61e886618870cfc0839956c88ad5fa7c134bb056376130b0aed6a7ab98d52024.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "005-the-beatles-abbey-road-1955f3c5": {
    albumId: "005-the-beatles-abbey-road-1955f3c5",
    editionNumber: 3,
    contentHash: "772df43eaad90b18",
    objectHash: "f93c8c5cb633863141d9a105b5e643bee29ee10b025df679a9802d2f2ed18700",
    trackCount: 17,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/f93c8c5cb633863141d9a105b5e643bee29ee10b025df679a9802d2f2ed18700.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/f93c8c5cb633863141d9a105b5e643bee29ee10b025df679a9802d2f2ed18700.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "006-nirvana-nevermind-0af5df5e": {
    albumId: "006-nirvana-nevermind-0af5df5e",
    editionNumber: 2,
    contentHash: "2a86565a358580f0",
    objectHash: "940c9a5f85651c8cbcb95e93122acb84f28b6ad3b598b4ef32e4c187cf28299d",
    trackCount: 13,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/940c9a5f85651c8cbcb95e93122acb84f28b6ad3b598b4ef32e4c187cf28299d.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/940c9a5f85651c8cbcb95e93122acb84f28b6ad3b598b4ef32e4c187cf28299d.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "007-fleetwood-mac-rumours-bc57e04c": {
    albumId: "007-fleetwood-mac-rumours-bc57e04c",
    editionNumber: 3,
    contentHash: "414abb016229da97",
    objectHash: "f42e526158350c0734ca1b251182dbea9b53db9fb46f25459d67d697a5532016",
    trackCount: 11,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/f42e526158350c0734ca1b251182dbea9b53db9fb46f25459d67d697a5532016.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/f42e526158350c0734ca1b251182dbea9b53db9fb46f25459d67d697a5532016.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "054-liz-phair-exile-in-guyville-2b33a458": {
    albumId: "054-liz-phair-exile-in-guyville-2b33a458",
    editionNumber: 5,
    contentHash: "c8496228067c3426",
    objectHash: "3da3d3ff11498d848e8e6c54bcb956cbafe9d22765ad055f84012ebe0e1f20a6",
    trackCount: 18,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/3da3d3ff11498d848e8e6c54bcb956cbafe9d22765ad055f84012ebe0e1f20a6.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/3da3d3ff11498d848e8e6c54bcb956cbafe9d22765ad055f84012ebe0e1f20a6.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "092-the-stooges-fun-house-9896fe5c": {
    albumId: "092-the-stooges-fun-house-9896fe5c",
    editionNumber: 4,
    contentHash: "ffd3fa7023be2acf",
    objectHash: "bcd1f36752a4b5b299ecfa8e1f46eb294d29f000a796e4f4ccb0b946385068e2",
    trackCount: 7,
    releaseHash: "835a3eadec751fea",
    editionPath: "objects/albums/bcd1f36752a4b5b299ecfa8e1f46eb294d29f000a796e4f4ccb0b946385068e2.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/bcd1f36752a4b5b299ecfa8e1f46eb294d29f000a796e4f4ccb0b946385068e2.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
} as const;

export type TrackEncyclopediaAlbumId = keyof typeof trackEncyclopediaAlbums;
