// Generated by scripts/build-track-encyclopedia.mjs. Do not edit by hand.
import type { TrackEncyclopediaAlbumEntry } from "../../types";

export const trackEncyclopediaMetadata = {
  "version": "1.0.0-pilot",
  "generatedAt": "2026-09-19T00:00:00Z",
  "albumCount": 8
} as const;

export const trackEncyclopediaAlbums = {
  "001-marvin-gaye-what-s-going-on-fd00dde9": {
    albumId: "001-marvin-gaye-what-s-going-on-fd00dde9",
    editionNumber: 4,
    contentHash: "449c11738b4a4676",
    objectHash: "030a139c5c59ef4c674a6b0b639af94ef419818414a755d2ee272bad06252f78",
    trackCount: 9,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/030a139c5c59ef4c674a6b0b639af94ef419818414a755d2ee272bad06252f78.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/030a139c5c59ef4c674a6b0b639af94ef419818414a755d2ee272bad06252f78.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "002-the-beach-boys-pet-sounds-eabcc325": {
    albumId: "002-the-beach-boys-pet-sounds-eabcc325",
    editionNumber: 1,
    contentHash: "b09e0a3f6b9d372f",
    objectHash: "f89d2d72d13c21ba12023e53c5bec191f87961ccee06e7692e42658352f10541",
    trackCount: 13,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/f89d2d72d13c21ba12023e53c5bec191f87961ccee06e7692e42658352f10541.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/f89d2d72d13c21ba12023e53c5bec191f87961ccee06e7692e42658352f10541.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "003-joni-mitchell-blue-9c3a8b85": {
    albumId: "003-joni-mitchell-blue-9c3a8b85",
    editionNumber: 1,
    contentHash: "03c972742edf5d9a",
    objectHash: "560189417ae7d43da35c8a39509857f3aa116a8e3bf117062ff5e30fdedcb04b",
    trackCount: 10,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/560189417ae7d43da35c8a39509857f3aa116a8e3bf117062ff5e30fdedcb04b.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/560189417ae7d43da35c8a39509857f3aa116a8e3bf117062ff5e30fdedcb04b.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "004-stevie-wonder-songs-in-the-key-of-life-0518d4f8": {
    albumId: "004-stevie-wonder-songs-in-the-key-of-life-0518d4f8",
    editionNumber: 1,
    contentHash: "898fc67f8c7aaa5e",
    objectHash: "15a086fa12b4bfaed685438322db65797d42c95f52815b17326e481c478655d6",
    trackCount: 21,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/15a086fa12b4bfaed685438322db65797d42c95f52815b17326e481c478655d6.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/15a086fa12b4bfaed685438322db65797d42c95f52815b17326e481c478655d6.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "005-the-beatles-abbey-road-1955f3c5": {
    albumId: "005-the-beatles-abbey-road-1955f3c5",
    editionNumber: 2,
    contentHash: "60c8394ddd63bf3d",
    objectHash: "76853d41c445d9dea3e3e95c3d8110bb63b8303e0ae599181d150688848d667f",
    trackCount: 17,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/76853d41c445d9dea3e3e95c3d8110bb63b8303e0ae599181d150688848d667f.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/76853d41c445d9dea3e3e95c3d8110bb63b8303e0ae599181d150688848d667f.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "006-nirvana-nevermind-0af5df5e": {
    albumId: "006-nirvana-nevermind-0af5df5e",
    editionNumber: 1,
    contentHash: "760c0dd6f1f4bc26",
    objectHash: "f99df8980ac146de85bda12de8dcf48038db08b12c7dc1092b89dea96b07af7e",
    trackCount: 13,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/f99df8980ac146de85bda12de8dcf48038db08b12c7dc1092b89dea96b07af7e.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/f99df8980ac146de85bda12de8dcf48038db08b12c7dc1092b89dea96b07af7e.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "054-liz-phair-exile-in-guyville-2b33a458": {
    albumId: "054-liz-phair-exile-in-guyville-2b33a458",
    editionNumber: 4,
    contentHash: "13de9e97abdf754c",
    objectHash: "497b264ea8835eb1fb2cf810bed368a4397174be5bbdc710c06452928b530102",
    trackCount: 18,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/497b264ea8835eb1fb2cf810bed368a4397174be5bbdc710c06452928b530102.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/497b264ea8835eb1fb2cf810bed368a4397174be5bbdc710c06452928b530102.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
  "092-the-stooges-fun-house-9896fe5c": {
    albumId: "092-the-stooges-fun-house-9896fe5c",
    editionNumber: 3,
    contentHash: "ee805c782c56bc4a",
    objectHash: "efd609a7260c9f173836bc1480fea6b56ccf130d5cfa3158524d2d11aa86a9cc",
    trackCount: 7,
    releaseHash: "4bca54f02f4ad8aa",
    editionPath: "objects/albums/efd609a7260c9f173836bc1480fea6b56ccf130d5cfa3158524d2d11aa86a9cc.json",
    load: async () => { const response = await fetch(new URL("./objects/albums/efd609a7260c9f173836bc1480fea6b56ccf130d5cfa3158524d2d11aa86a9cc.json", import.meta.url), { cache: "no-store" }); if (!response.ok) throw new Error(`Track encyclopedia request failed: ${response.status}`); return (await response.json()) as TrackEncyclopediaAlbumEntry; },
  },
} as const;

export type TrackEncyclopediaAlbumId = keyof typeof trackEncyclopediaAlbums;
